version: '3.8'
services:
  text_editor_db:
    image: postgres:15-alpine3.18
    environment:
      POSTGRES_DB: text_editor_db
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: 21042005
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d", "db_prod" ]
      timeout: 60s
      retries: 10
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  text-editor:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL:  jdbc:postgresql://text_editor_db:5432/text_editor_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 21042005
    ports:
      - "8080:8080"
    depends_on:
      text_editor_db:
        condition: service_healthy
    logging:
      driver: fluentd
      options:
        fluentd-address: host.docker.internal:24224
        tag: editor.app
